{% set name = "thriftpy2" %}
{% set version = "0.5.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Thriftpy/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 16f3fd24f7778416d70b7cbd2cefce28e49ba72abe9f12471ae7697b09c70c25

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed -vv
  skip: true  # [py<37]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
  host:
    - pip
    - python
    - wheel
    - setuptools >=68
    - toml
    - cython >=0.28.4,<4
  run:
    - python
    - ply >=3.4,<4.0
    - six >=1.15,<2

test:
  source_files:
    - tests
    - examples
  imports:
    - thriftpy2
    - thriftpy2.parser
    - thriftpy2.protocol
    - thriftpy2.transport
  commands:
    - pip check
    - cd tests && pytest test_base.py
  requires:
    - pip
    - pytest >=6.1.1,<8.2.0
    - pytest-asyncio

about:
  home: https://thriftpy2.readthedocs.io
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Pure python implementation of Apache Thrift.
  description: |
    ThriftPy2 is a pure python implementation of Apache Thrift in a pythonic way.

    The official thrift python lib is not pythonic at all, it needs a complicated process of installation, and 
    the generated sdk is very ugly. Everytime the thrift file changed you have to re-generate the sdk 
    which causes more pain in development.

    ThriftPy2 helps that, it's compatible with Apache Thrift so you no longer need to install 'thrift' 
    package, it can import thrift file on the fly so you no longer need to re-generate the sdk again 
    and again and again.
  doc_url: https://thriftpy2.readthedocs.io
  dev_url: https://github.com/Thriftpy/thriftpy2

extra:
  recipe-maintainers:
    - xhochy
