travis:
  secure:
    BINSTAR_TOKEN: muSm675x3fYw0912U2NyFXI9JooXhizY/gZad/bpiWyEZI4NGIKI/3adT4C/k1EYcb/kPktD4u3LscmdQKhUvL6tpN89ZCP0Rf2aH3K8tNMDAYz+QAPZvdAFsoYKnhIqCrSpOTsUygSw2Yh+tgMABtOYrvJj+HY9+yNZJAeWhQNZdGf+TAcAEeXwHXL7pyyt+sW67S2LH+TtsjxSWerdN/4yOOsPBWlOIxxUfGH961eATBitTQ/ZtgkLQH7NQPJ9Bk55LkZUXBTCrLKh4GsacnEq5Mj1kZfJROr6IY/BcYXTXQQOJKHHuZPL05sJw6+B3At9D8PI/tyIeOaEu0IbDttVDQgR9HkVTgaYwca3j9Fpi+m7lksJNThmwo36SbWAs28SgRP/moss3xWdoXnfqy3ZJXnkvGHY4tPipcoEJD94JRIAUWu+9FaNw9wGrGSaUATtIMCca+RNznYsrjBUIlRlbLx92Qz5lY+fUm7tJEluhVKRIx/JLRCNUTxOBOMsUHBEoGQmalJjflSNJzE+OtXXjuTbnXACzaRpkAjYUhi+kdtpPlM30FtZ+SYsDLer9B2HyI5A+aoM90UpMiyFC+GmjGXPfVqzzg1EKgA5Vkh26VPf8UHGgjPYNh3uQFCGvnbiEEvy2KVX9DH11A75vfzr5A0cgJ5iDze1FXoO/5I=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
